CleanArchi.Web/Controllers/AmenityController.cs
using CleanArchi.Application.Common.Interfaces;
using CleanArchi.Application.Common.Utility;
using CleanArchi.Domain.Entities;
using CleanArchi.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CleanArchi.Web.Controllers
{
    //ログイン中のadminのみアクセス可能
    [Authorize(Roles = SD.Role_Admin)]
    public class AmenityController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public AmenityController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            //var amenities = _db.VillaNumbers.Include(u => u.Villa).ToList();
            var amenities = _unitOfWork.Amenity.GetAll(includeProperties: nameof(Villa));

            return View(amenities);
        }

        public IActionResult Create()
        {
            AmenityVM amenityVM = new()
            {
                //AmenityList = _db.Villas.ToList().Select(u => new SelectListItem
                //{
                //	Text = u.Name,
                //	Value = u.Id.ToString(),
                //})

                VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString(),
                })
            };

            return View(amenityVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(AmenityVM obj)
        {

            if (ModelState.IsValid)
            {
                _unitOfWork.Amenity.Add(obj.Amenity);
                _unitOfWork.Save();
                TempData["success"] = "正常に作成しました。";
                return RedirectToAction(nameof(Index));
            }

            obj.VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString(),
            });
            return View(obj);

        }

        public IActionResult Update(int amenityId)
        {

            AmenityVM amenityVM = new()
            {
                VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString(),
                }),
                Amenity = _unitOfWork.Amenity.Get(u => u.Id == amenityId)
            };

            if (amenityVM.Amenity == null)
            {
                TempData["error"] = "指定データがありません。";
                return RedirectToAction("Error", "Home");
            }
            return View(amenityVM);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(AmenityVM obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Amenity.Update(obj.Amenity);
                _unitOfWork.Save();
                TempData["success"] = "正常に更新しました。";
                return RedirectToAction(nameof(Index));
            }

            obj.VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString(),
            });
            return View(obj);

        }

        public IActionResult Delete(int amenityId)
        {
            AmenityVM amenityVM = new()
            {
                VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString(),
                }),

                Amenity = _unitOfWork.Amenity.Get(u => u.Id == amenityId)
            };

            if (amenityVM.Amenity == null)
            {
                TempData["error"] = "指定データがありません。";
                return RedirectToAction("Error", "Home");
            }
            return View(amenityVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(AmenityVM obj)
        {
            //Amenity? objFromDb = _db.VillaNumbers.FirstOrDefault(u => u.Id == obj.Amenity.Id);
            Amenity? objFromDb = _unitOfWork.Amenity.Get(u => u.Id == obj.Amenity.Id);
            if (objFromDb is not null)
            {
                _unitOfWork.Amenity.Remove(objFromDb);
                _unitOfWork.Save();
                TempData["success"] = "正常に削除しました。";
                return RedirectToAction(nameof(Index));
            }
            TempData["error"] = "削除出来ませんでした。";
            return View(obj);
        }

        //public async Task<IActionResult> Index()
        //{
        //    var amenities = await _db.VillaNumbers.Include(u=>u.Villa).ToListAsync();

        //    return View(amenities);
        //}

        //public async Task<IActionResult> Create()
        //{
        //    AmenityVM amenityVM = new()
        //    {
        //        AmenityList = (await _db.Villas.ToListAsync()).Select(u => new SelectListItem
        //        {
        //            Text = u.Name,
        //            Value = u.Id.ToString(),
        //        })
        //    };

        //    //IEnumerable<SelectListItem> list = (await _db.Villas.ToListAsync()).Select(u => new SelectListItem
        //    //{
        //    //    Text = u.Name,
        //    //    Value = u.Id.ToString(),
        //    //});

        //    ////ViewData["AmenityList"] = list;
        //    //ViewBag.AmenityList = list;
        //    return View(amenityVM);
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create(AmenityVM obj)
        //{
        //    //ルーム番号存在チェック
        //    bool roomNumberExists = _db.VillaNumbers.Any(u => u.Id == obj.Amenity.Id);

        //    if (ModelState.IsValid && !roomNumberExists)
        //    {
        //        _db.VillaNumbers.Add(obj.Amenity);
        //        await _db.SaveChangesAsync();
        //        TempData["success"] = "正常に作成しました。";
        //        return RedirectToAction(nameof(Index));
        //    }
        //    if (roomNumberExists)
        //    {
        //        TempData["error"] = "指定部屋番号は既に存在する番号です。";
        //    }
        //    else
        //    {
        //        TempData["error"] = "作成出来ませんでした。";
        //    }

        //    obj.AmenityList = (await _db.Villas.ToListAsync()).Select(u => new SelectListItem
        //    {
        //        Text = u.Name,
        //        Value = u.Id.ToString(),
        //    });
        //    return View(obj);

        //}

        //public async Task<IActionResult> Update(int amenityId)
        //{

        //    AmenityVM amenityVM = new()
        //    {
        //        AmenityList = (await _db.Villas.ToListAsync()).Select(u => new SelectListItem
        //        {
        //            Text = u.Name,
        //            Value = u.Id.ToString(),
        //        }),
        //        Amenity = await _db.VillaNumbers.AsNoTracking().FirstOrDefaultAsync(u => u.Id == amenityId)
        //    };

        //    if (amenityVM.Amenity == null)
        //    {
        //        TempData["error"] = "指定データがありません。";
        //        return RedirectToAction("Error", "Home");
        //    }
        //    return View(amenityVM);
        //}


        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Update(AmenityVM obj)
        //{

        //    if (ModelState.IsValid )
        //    {
        //        _db.VillaNumbers.Update(obj.Amenity);
        //        await _db.SaveChangesAsync();
        //        TempData["success"] = "正常に更新しました。";
        //        return RedirectToAction(nameof(Index));
        //    }

        //    obj.AmenityList = (await _db.Villas.ToListAsync()).Select(u => new SelectListItem
        //    {
        //        Text = u.Name,
        //        Value = u.Id.ToString(),
        //    });
        //    return View(obj);

        //}

        //public async Task<IActionResult> Delete(int amenityId)
        //{
        //    AmenityVM amenityVM = new()
        //    {
        //        AmenityList = (await _db.Villas.ToListAsync()).Select(u => new SelectListItem
        //        {
        //            Text = u.Name,
        //            Value = u.Id.ToString(),
        //        }),
        //        Amenity = await _db.VillaNumbers.AsNoTracking().FirstOrDefaultAsync(u => u.Id == amenityId)
        //    };

        //    if (amenityVM.Amenity == null)
        //    {
        //        TempData["error"] = "指定データがありません。";
        //        return RedirectToAction("Error", "Home");
        //    }
        //    return View(amenityVM);
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Delete(AmenityVM obj)
        //{
        //    Amenity? objFromDb = await _db.VillaNumbers.FirstOrDefaultAsync(u => u.Id == obj.Amenity.Id);
        //    if (objFromDb is not null)
        //    {
        //        _db.VillaNumbers.Remove(objFromDb);
        //        await _db.SaveChangesAsync();
        //        TempData["success"] = "正常に削除しました。";
        //        return RedirectToAction(nameof(Index));
        //    }
        //    TempData["error"] = "削除出来ませんでした。";
        //    return View(obj);
        //}
    }
}

CleanArchi.Web/Controllers/VillaController.cs
using CleanArchi.Application.Common.Interfaces;
using CleanArchi.Domain.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CleanArchi.Web.Controllers
{
    //ログイン中のみアクセス可
    [Authorize]
    public class VillaController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
		private readonly IWebHostEnvironment _webHostEnvironment;

        public VillaController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
			_unitOfWork = unitOfWork;
			_webHostEnvironment = webHostEnvironment;

		}

		public IActionResult Index()
		{
			var villas = _unitOfWork.Villa.GetAll();
			return View(villas);
		}

		public IActionResult Create()
		{
			//int x = 10;
			//int y = 0;
			//int z = x / y;
			return View();
		}

		[HttpPost]
		public IActionResult Create(Villa obj)
		{
			if (obj.Name == obj.Description)
			{
				ModelState.AddModelError("name", "説明が名前と一致していません。");
			}

			if (ModelState.IsValid)
			{
				if (obj.Image != null)
				{
					string fileName = Guid.NewGuid().ToString() + Path.GetExtension(obj.Image.FileName);
					string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, @"images\VillaImage");
					using (var fileStream = new FileStream(Path.Combine(imagePath, fileName), FileMode.Create))
					//アップロードファイルを指定のフォルダにコピー保存する。
					obj.Image.CopyTo(fileStream);
					obj.ImageUrl = @"\images\VillaImage\" + fileName;
				}
				else
				{
					obj.ImageUrl = "https://placehold.co/600x400";
				}

				_unitOfWork.Villa.Add(obj);
				_unitOfWork.Save();
				TempData["success"] = "正常に新規作成しました。";
				return RedirectToAction("Index");
			}
			TempData["error"] = "作成出来ませんでした。";
			return View();

		}

		public IActionResult Update(int villaId)
		{
			Villa? obj = _unitOfWork.Villa.Get(u => u.Id == villaId);
			if (obj == null)
			{
				TempData["error"] = "指定データがありません。";
				return RedirectToAction("Error", "Home");
			}
			return View(obj);
		}

		[HttpPost]
		public IActionResult Update(Villa obj)
		{
			if (ModelState.IsValid && obj.Id > 0)
			{
                if (obj.Image != null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(obj.Image.FileName);
                    string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, @"images\VillaImage");

					//更新前のイメージを削除
					if (!string.IsNullOrEmpty(obj.ImageUrl))
					{
						var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
						if (System.IO.File.Exists(oldImagePath))
						{
							System.IO.File.Delete(oldImagePath);
                        }
					}

                    using (var fileStream = new FileStream(Path.Combine(imagePath, fileName), FileMode.Create))
                        //アップロードファイルを指定のフォルダにコピー保存する。
                        obj.Image.CopyTo(fileStream);
                    obj.ImageUrl = @"\images\VillaImage\" + fileName;
                }
               
                _unitOfWork.Villa.Update(obj);
				_unitOfWork.Save();
				TempData["success"] = "正常に更新しました。";
				return RedirectToAction("Index");
			}
			TempData["error"] = "更新出来ませんでした。";
			return View();

		}

		public IActionResult Delete(int villaId)
		{
			Villa? obj = _unitOfWork.Villa.Get(u => u.Id == villaId);
			if (obj == null)
			{
				TempData["error"] = "指定データがありません。";
				return RedirectToAction("Error", "Home");
			}
			return View(obj);
		}

		[HttpPost]
		public IActionResult Delete(Villa obj)
		{
			Villa? objFromDb = _unitOfWork.Villa.Get(u => u.Id == obj.Id);
			if (objFromDb is not null)
			{
                //イメージを削除
                if (!string.IsNullOrEmpty(objFromDb.ImageUrl))
                {
                    var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, objFromDb.ImageUrl.TrimStart('\\'));
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }
                _unitOfWork.Villa.Remove(objFromDb);
				_unitOfWork.Save();
				TempData["success"] = "正常に削除しました。";
				return RedirectToAction("Index");
			}
			TempData["error"] = "削除出来ませんでした。";
			return View();
		}

		//public async Task<IActionResult> Index()
  //      {
  //          var villas = await _db.Villas.ToListAsync();
  //          return View(villas);
  //      }

  //      public IActionResult Create()
  //      {
  //          //int x = 10;
  //          //int y = 0;
  //          //int z = x / y;
  //          return View();
  //      }

  //      [HttpPost]
  //      public async Task<IActionResult> Create(Villa obj)
  //      {
  //          if (ModelState.IsValid)
  //          {
  //              _db.Villas.Add(obj);
  //              await _db.SaveChangesAsync();
  //              TempData["success"] = "正常に新規作成しました。";
  //              return RedirectToAction("Index");
  //          }
  //          TempData["error"] = "作成出来ませんでした。";
  //          return View();

  //      }

  //      public async Task<IActionResult> Update(int villaId)
  //      {
  //          Villa? obj = await _db.Villas.FirstOrDefaultAsync(u=>u.Id==villaId);
  //          if (obj == null)
  //          {
  //              TempData["error"] = "指定データがありません。";
  //              return RedirectToAction("Error", "Home");
  //          }
  //          return View(obj);
  //      }


  //      [HttpPost]
  //      public async Task<IActionResult> Update(Villa obj)
  //      {
  //          if (ModelState.IsValid && obj.Id > 0)
  //          {
  //              _db.Villas.Update(obj);
  //              await _db.SaveChangesAsync();
  //              TempData["success"] = "正常に更新しました。";
  //              return RedirectToAction("Index");
  //          }
  //          TempData["error"] = "更新出来ませんでした。";
  //          return View();

  //      }

  //      public async Task<IActionResult> Delete(int villaId)
  //      {
  //          Villa? obj = await _db.Villas.FirstOrDefaultAsync(u => u.Id == villaId);
  //          if (obj == null)
  //          {
  //              TempData["error"] = "指定データがありません。";
  //              return RedirectToAction("Error", "Home");
  //          }
  //          return View(obj);
  //      }

  //      [HttpPost]
  //      public async Task<IActionResult> Delete(Villa obj)
  //      {
  //          Villa? objFromDb = await _db.Villas.FirstOrDefaultAsync(u => u.Id == obj.Id);
  //          if (objFromDb is not null)
  //          {
  //              _db.Villas.Remove(objFromDb);
  //              await _db.SaveChangesAsync();
  //              TempData["success"] = "正常に削除しました。";
  //              return RedirectToAction("Index");
  //          }
  //          TempData["error"] = "削除出来ませんでした。";
  //          return View();
  //      }
    }
}

CleanArchi.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ja" data-bs-theme="dark">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CleanArchi.Web</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.1/css/bootstrap.min.css" integrity="sha512-Z/def5z5u2aR89OuzYcxmDJ0Bnd5V1cKqBEbvLOiUNWdg9PQeXVvXLI90SE4QOHGlfLqUnDNVAYyZi8UwUTmWQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CleanArchi.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/spinner.css"/>
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/resort.png" style="width:35px" />CleanArchi.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                コンテンツマネジメント
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Villa" asp-action="Index">ヴィラ</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="VillaNumber" asp-action="Index">ヴィラ番号</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Amenity" asp-action="Index">アメニティ</a></li>
                            </ul>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main">
            <div class="loading spinner" style="display:none;"></div>
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-dark text-muted">
        <div class="container text-center">
            &copy; 2023 - CleanArchi.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @* jqueryライブラリunobtrusive-ajaxを使う場合 *@
    @* <script src="~/js/jquery.unobtrusive-ajax.min.js"></script> *@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CleanArchi.Web/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
	<script type="text/javascript">
		toastr.success('@TempData["success"]');
	</script>
}

@if (TempData["error"] != null)
{
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
	<script type="text/javascript">
		toastr.error('@TempData["error"]');
	</script>
}

CleanArchi.Web/Views/Shared/_VillaDetail.cshtml
@model Villa
<div class="row">
    <div class="col-12 col-md-5">
        <img src="@Model.ImageUrl" style="border-radius:10px;" width="100%" />
    </div>
    <div class="col-12 col-md-7">
        <div class="row p-2">
            <div class="col-12">
                <p class="card-title text-warning" style="font-size:xx-large">@Model.Name</p>
                <p class="card-text" style="font-size:large">
                    @Html.Raw(Model.Description)
                </p>
                @if (Model.VillaAmenity != null && Model.VillaAmenity.Count() > 0)
                {
                    <p class="h5 text-white">Villa Amenities</p>
                    <ul>
                        @foreach (var amenity in Model.VillaAmenity)
                        {
                            <li>@amenity.Name</li>
                        }
                    </ul>
                }
            </div>
        </div>
        <div class="row col-12">
            <span class="text-end p-0 pt-3 m-0">
                <span class="float-right">Max Occupancy : @Model.Occupancy adults </span><br />
                <span class="float-right pt-1">Villa Size : @Model.Sqft sqft</span><br />
                <p class="text-warning font-weight-bold pt-1">
                    USD
                    <span style=" #ff6a00">
                        @Model.Price.ToString("c") / night
                    </span>
                </p>
            </span>
        </div>
    </div>
</div>

CleanArchi.Web/Views/Shared/_VillaList.cshtml
@model HomeVM
<div id="VillasList">
    <div class="row px-lg-5 m-lg-4 m-sm-0 px-sm-0" style="--bs-gutter-x:0">
    @foreach (var villa in Model.VillaList)
    {
        <div class="p-4 col-md-12 col-lg-6">
            <div class="row" style="border-radius:5px; border: 1px solid #aaa">
                <div class="col-4 p-2">
                    <img class="d-block w-100" style="border-radius:5px;" src="@villa.ImageUrl">
                </div>
                <div class="col-8">
                    <div class="d-flex justify-content-between">
                        <p class="card-title text-warning" style="font-size:xx-large">@villa.Name</p>
                        <div class="pt-2">
                            <button type="button" class="btn btn-sm btn-outline-success" data-bs-toggle="modal" data-bs-target='#exampleModal-@(villa.Id)'>
                                詳細
                            </button>
                        </div>
                    </div>
                    <p class="card-text">
                        @Html.Raw(villa.Description)
                    </p>
                </div>
                <div class="col-12">
                    <div class="row pb-3 pt-2">
                        <div class="col-4">
                            @if (Model.CheckInDate >= DateOnly.FromDateTime(DateTime.Now))
                            {
                                if (villa.IsAvailable)
                                {
                                    <a class="btn btn-success form-control btn-block">
                                        予約
                                    </a>
                                }
                                else
                                {
                                    <a class="btn btn-outline-danger disabled form-control btn-block">
                                        完売
                                    </a>

                                }
                            }
                        </div>
                        <div class="col-4">
                            <span class="">Max Occupancy : @villa.Occupancy adults </span><br />
                            <span class=" pt-1">Villa Size : @villa.Sqft sqft</span><br />
                        </div>
                        <div class="col-4">
                            <span class="text-warning float-end font-weight-bold pt-1" style="font-size:25px;">
                                USD
                                <span style="border-bottom:1px solid #ff6a00">
                                    @villa.Price.ToString("c")
                                </span>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="exampleModal-@(villa.Id)" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-xl" style="border: 1px solid #aaa; border-radius:7px;">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-3 text-success" id="exampleModalLabel">ヴィラ 詳細 - @villa.Name</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="閉じる"></button>
                    </div>
                    <div class="modal-body m-0">
                        <partial name="_VillaDetail" model="@villa" />
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline-danger" data-bs-dismiss="modal">閉じる</button>
                    </div>

                </div>
            </div>
        </div>
    }
</div>
</div>