CleanArchi.Web/Controllers/VillaNumberController.cs
using CleanArchi.Application.Common.Interfaces;
using CleanArchi.Domain.Entities;
using CleanArchi.Infrastructure.Data;
using CleanArchi.Infrastructure.Repository;
using CleanArchi.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CleanArchi.Web.Controllers
{
    public class VillaNumberController : Controller
    {
		private readonly IUnitOfWork _unitOfWork;

		public VillaNumberController(IUnitOfWork unitOfWork)
        {
			_unitOfWork = unitOfWork;
        }

        public IActionResult Index()
		{
			//var villaNumbers = _db.VillaNumbers.Include(u => u.Villa).ToList();
			var villaNumbers = _unitOfWork.VillaNumber.GetAll(includeProperties: nameof(Villa));

			return View(villaNumbers);
		}

		public IActionResult Create()
		{
			VillaNumberVM villaNumberVM = new()
			{
				//VillaList = _db.Villas.ToList().Select(u => new SelectListItem
				//{
				//	Text = u.Name,
				//	Value = u.Id.ToString(),
				//})
				
				VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
				{
					Text = u.Name,
					Value = u.Id.ToString(),
				})
			};

			return View(villaNumberVM);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create(VillaNumberVM obj)
		{
			//ルーム番号存在チェック
			//bool roomNumberExists = _db.VillaNumbers.Any(u => u.Villa_Number == obj.VillaNumber.Villa_Number);
			bool roomNumberExists = _unitOfWork.VillaNumber.Any(u => u.Villa_Number == obj.VillaNumber.Villa_Number);

			if (ModelState.IsValid && !roomNumberExists)
			{
				_unitOfWork.VillaNumber.Add(obj.VillaNumber);
				_unitOfWork.Save();
				TempData["success"] = "正常に作成しました。";
				return RedirectToAction(nameof(Index));
			}
			if (roomNumberExists)
			{
				TempData["error"] = "指定部屋番号は既に存在する番号です。";
			}
			else
			{
				TempData["error"] = "作成出来ませんでした。";
			}

			obj.VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
			{
				Text = u.Name,
				Value = u.Id.ToString(),
			});
			return View(obj);

		}

		public IActionResult Update(int villaNumberId)
		{

			VillaNumberVM villaNumberVM = new()
			{
				VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
				{
					Text = u.Name,
					Value = u.Id.ToString(),
				}),
				//VillaNumber = _db.VillaNumbers.FirstOrDefault(u => u.Villa_Number == villaNumberId)
				VillaNumber = _unitOfWork.VillaNumber.Get(u => u.Villa_Number == villaNumberId)
			};

			if (villaNumberVM.VillaNumber == null)
			{
				TempData["error"] = "指定データがありません。";
				return RedirectToAction("Error", "Home");
			}
			return View(villaNumberVM);
		}


		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Update(VillaNumberVM obj)
		{
			if (ModelState.IsValid)
			{
				_unitOfWork.VillaNumber.Update(obj.VillaNumber);
				_unitOfWork.Save();
				TempData["success"] = "正常に更新しました。";
				return RedirectToAction(nameof(Index));
			}

			obj.VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
			{
				Text = u.Name,
				Value = u.Id.ToString(),
			});
			return View(obj);

		}

		public IActionResult Delete(int villaNumberId)
		{
			VillaNumberVM villaNumberVM = new()
			{
				VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
				{
					Text = u.Name,
					Value = u.Id.ToString(),
				}),

				VillaNumber = _unitOfWork.VillaNumber.Get(u => u.Villa_Number == villaNumberId)
			};

			if (villaNumberVM.VillaNumber == null)
			{
				TempData["error"] = "指定データがありません。";
				return RedirectToAction("Error", "Home");
			}
			return View(villaNumberVM);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Delete(VillaNumberVM obj)
		{
			//VillaNumber? objFromDb = _db.VillaNumbers.FirstOrDefault(u => u.Villa_Number == obj.VillaNumber.Villa_Number);
			VillaNumber? objFromDb = _unitOfWork.VillaNumber.Get(u => u.Villa_Number == obj.VillaNumber.Villa_Number);
			if (objFromDb is not null)
			{
				_unitOfWork.VillaNumber.Remove(objFromDb);
				_unitOfWork.Save();
				TempData["success"] = "正常に削除しました。";
				return RedirectToAction(nameof(Index));
			}
			TempData["error"] = "削除出来ませんでした。";
			return View(obj);
		}

		//public async Task<IActionResult> Index()
		//{
		//    var villaNumbers = await _db.VillaNumbers.Include(u=>u.Villa).ToListAsync();

		//    return View(villaNumbers);
		//}

		//public async Task<IActionResult> Create()
		//{
		//    VillaNumberVM villaNumberVM = new()
		//    {
		//        VillaList = (await _db.Villas.ToListAsync()).Select(u => new SelectListItem
		//        {
		//            Text = u.Name,
		//            Value = u.Id.ToString(),
		//        })
		//    };

		//    //IEnumerable<SelectListItem> list = (await _db.Villas.ToListAsync()).Select(u => new SelectListItem
		//    //{
		//    //    Text = u.Name,
		//    //    Value = u.Id.ToString(),
		//    //});

		//    ////ViewData["VillaList"] = list;
		//    //ViewBag.VillaList = list;
		//    return View(villaNumberVM);
		//}

		//[HttpPost]
		//[ValidateAntiForgeryToken]
		//public async Task<IActionResult> Create(VillaNumberVM obj)
		//{
		//    //ルーム番号存在チェック
		//    bool roomNumberExists = _db.VillaNumbers.Any(u => u.Villa_Number == obj.VillaNumber.Villa_Number);

		//    if (ModelState.IsValid && !roomNumberExists)
		//    {
		//        _db.VillaNumbers.Add(obj.VillaNumber);
		//        await _db.SaveChangesAsync();
		//        TempData["success"] = "正常に作成しました。";
		//        return RedirectToAction(nameof(Index));
		//    }
		//    if (roomNumberExists)
		//    {
		//        TempData["error"] = "指定部屋番号は既に存在する番号です。";
		//    }
		//    else
		//    {
		//        TempData["error"] = "作成出来ませんでした。";
		//    }

		//    obj.VillaList = (await _db.Villas.ToListAsync()).Select(u => new SelectListItem
		//    {
		//        Text = u.Name,
		//        Value = u.Id.ToString(),
		//    });
		//    return View(obj);

		//}

		//public async Task<IActionResult> Update(int villaNumberId)
		//{

		//    VillaNumberVM villaNumberVM = new()
		//    {
		//        VillaList = (await _db.Villas.ToListAsync()).Select(u => new SelectListItem
		//        {
		//            Text = u.Name,
		//            Value = u.Id.ToString(),
		//        }),
		//        VillaNumber = await _db.VillaNumbers.AsNoTracking().FirstOrDefaultAsync(u => u.Villa_Number == villaNumberId)
		//    };

		//    if (villaNumberVM.VillaNumber == null)
		//    {
		//        TempData["error"] = "指定データがありません。";
		//        return RedirectToAction("Error", "Home");
		//    }
		//    return View(villaNumberVM);
		//}


		//[HttpPost]
		//[ValidateAntiForgeryToken]
		//public async Task<IActionResult> Update(VillaNumberVM obj)
		//{

		//    if (ModelState.IsValid )
		//    {
		//        _db.VillaNumbers.Update(obj.VillaNumber);
		//        await _db.SaveChangesAsync();
		//        TempData["success"] = "正常に更新しました。";
		//        return RedirectToAction(nameof(Index));
		//    }

		//    obj.VillaList = (await _db.Villas.ToListAsync()).Select(u => new SelectListItem
		//    {
		//        Text = u.Name,
		//        Value = u.Id.ToString(),
		//    });
		//    return View(obj);

		//}

		//public async Task<IActionResult> Delete(int villaNumberId)
		//{
		//    VillaNumberVM villaNumberVM = new()
		//    {
		//        VillaList = (await _db.Villas.ToListAsync()).Select(u => new SelectListItem
		//        {
		//            Text = u.Name,
		//            Value = u.Id.ToString(),
		//        }),
		//        VillaNumber = await _db.VillaNumbers.AsNoTracking().FirstOrDefaultAsync(u => u.Villa_Number == villaNumberId)
		//    };

		//    if (villaNumberVM.VillaNumber == null)
		//    {
		//        TempData["error"] = "指定データがありません。";
		//        return RedirectToAction("Error", "Home");
		//    }
		//    return View(villaNumberVM);
		//}

		//[HttpPost]
		//[ValidateAntiForgeryToken]
		//public async Task<IActionResult> Delete(VillaNumberVM obj)
		//{
		//    VillaNumber? objFromDb = await _db.VillaNumbers.FirstOrDefaultAsync(u => u.Villa_Number == obj.VillaNumber.Villa_Number);
		//    if (objFromDb is not null)
		//    {
		//        _db.VillaNumbers.Remove(objFromDb);
		//        await _db.SaveChangesAsync();
		//        TempData["success"] = "正常に削除しました。";
		//        return RedirectToAction(nameof(Index));
		//    }
		//    TempData["error"] = "削除出来ませんでした。";
		//    return View(obj);
		//}
	}
}

CleanArchi.Web/Views/VillaNumber/Create.cshtml
@model VillaNumberVM

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">新規登録</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row">
            <div class="p-3">
                <div class="form-floating py-2 col-12">
                    <select asp-for="@Model.VillaNumber.VillaId" asp-items="@Model.VillaList" class="form-select border shadow">
                        <option disabled selected>ヴィラを選択してください</option>
                    </select>
                    <label asp-for="VillaNumber.VillaId" class="ms-2"></label>
                    <span asp-validation-for="VillaNumber.VillaId" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="VillaNumber.Villa_Number" class="form-control border shadow" />
                    <label asp-for="VillaNumber.Villa_Number" class="ms-2"></label>
                    <span asp-validation-for="VillaNumber.Villa_Number" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="VillaNumber.SpecialDetails" class="form-control border shadow" />
                    <label asp-for="VillaNumber.SpecialDetails" class="ms-2"></label>
                    <span asp-validation-for="VillaNumber.SpecialDetails" class="text-danger"></span>
                </div>
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-success w-100">
                            <i class="bi bi-check-circle"></i> 登録
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="VillaNumber" asp-action="Index" class="btn btn-secondary w-100">
                            <i class="bi bi-x-circle"></i> 戻る
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

CleanArchi.Web/Views/VillaNumber/Delete.cshtml
@model VillaNumberVM

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">削除</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row">
            <input asp-for="VillaNumber.Villa_Number" hidden />
            <div class="p-3">
                <div class="form-floating py-2 col-12">
                    <select disabled asp-for="@Model.VillaNumber.VillaId" asp-items="@Model.VillaList" class="form-select border shadow">
                        <option disabled selected>ヴィラを選択してください</option>
                    </select>
                    <label asp-for="VillaNumber.VillaId" class="ms-2"></label>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="VillaNumber.Villa_Number" disabled class="form-control border shadow" />
                    <label asp-for="VillaNumber.Villa_Number" class="ms-2"></label>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="VillaNumber.SpecialDetails" disabled class="form-control border shadow" />
                    <label asp-for="VillaNumber.SpecialDetails" class="ms-2"></label>
                </div>
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-danger w-100">
                            <i class="bi bi-check-circle"></i> 削除
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="VillaNumber" asp-action="Index" class="btn btn-secondary w-100">
                            <i class="bi bi-x-circle"></i> 戻る
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

CleanArchi.Web/Views/VillaNumber/Index.cshtml
@model IEnumerable<VillaNumber>
<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">ヴィラ番号一覧</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <div class="row pb-3">
            <div class="col-6 offset-6 text-end">
                <a asp-controller="VillaNumber" asp-action="Create" class="btn btn-secondary">
                    <i class="bi bi-plus-circle"></i> 新規登録
                </a>
            </div>
        </div>

        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>
                        ヴィラ名
                    </th>
                    <th>ヴィラ番号</th>
                    <th>備考</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td>@obj.Villa.Name</td>
                        <td>@obj.Villa_Number</td>
                        <td>@obj.SpecialDetails</td>
                        <td>
                            <div>
                                <a asp-controller="VillaNumber" asp-action="Update" asp-route-villaNumberId="@obj.Villa_Number" class="btn btn-success mx-2">
                                    <i class="bi bi-pencil-square"></i> 編集
                                </a>
                                <a asp-controller="VillaNumber" asp-action="Delete" asp-route-villaNumberId="@obj.Villa_Number" class="btn btn-danger mx-2">
                                    <i class="bi bi-trash-fill"></i> 削除
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

CleanArchi.Web/Views/VillaNumber/Update.cshtml
@model VillaNumberVM

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">編集</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row">
            <input asp-for="VillaNumber.Villa_Number" hidden />
            <div class="p-3">
                <div class="form-floating py-2 col-12">
                    <select asp-for="@Model.VillaNumber.VillaId" asp-items="@Model.VillaList" class="form-select border shadow">
                        <option disabled selected>ヴィラを選択してください</option>
                    </select>
                    <label asp-for="VillaNumber.VillaId" class="ms-2"></label>
                    <span asp-validation-for="VillaNumber.VillaId" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="VillaNumber.Villa_Number" disabled class="form-control border shadow" />
                    <label asp-for="VillaNumber.Villa_Number" class="ms-2"></label>
                    <span asp-validation-for="VillaNumber.Villa_Number" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="VillaNumber.SpecialDetails" class="form-control border shadow" />
                    <label asp-for="VillaNumber.SpecialDetails" class="ms-2"></label>
                    <span asp-validation-for="VillaNumber.SpecialDetails" class="text-danger"></span>
                </div>
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-success w-100">
                            <i class="bi bi-check-circle"></i> 編集
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="VillaNumber" asp-action="Index" class="btn btn-secondary w-100">
                            <i class="bi bi-x-circle"></i> 戻る
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}